theme: jekyll-theme-minimal
title: Coffee Rings – Info Pages
description: "Privacy & Support for the Coffee Rings app"
logo: /assets/coffeerings.png
show_downloads: false
github:
  is_project_page: false
  is_user_page: false
  repository_url: ""
  owner_url: ""
